puts "🏕 Seeding activities..."
activity1 = Activity.create(name: 'Archery', difficulty: 2)
activity2 = Activity.create(name: 'Swimming', difficulty: 3)
activity3 = Activity.create(name: 'Photography', difficulty: 2)
activity4 = Activity.create(name: 'Arts & Crafts', difficulty: 5)
activity5 = Activity.create(name: 'Kayaking', difficulty: 3)
activity6 = Activity.create(name: 'Fencing', difficulty: 4)
activity7 = Activity.create(name: 'Canoeing', difficulty: 3)
activity8 = Activity.create(name: 'Windsurfing', difficulty: 5)

service1 = Service.create(name:'massage', price:1000 )
service2 = Service.create(name:'facial', price:2000)
service3 = Service.create(name: 'sauna', price:3000)
service4 = Service.create(name: 'hotstone',price:4000 )
service5 = Service.create(name: 'turkish massage',price:5000)